# A example scrape configuration for running Prometheus with
# DigitalOcean.

scrape_configs:
  # Make Prometheus scrape itself for metrics.
  - job_name: prometheus
    scrape_interval: 10s
    static_configs:
      - targets: [\"localhost:9090\"]

  # Discover Node Exporter instances to scrape.
  - job_name: node

    digitalocean_sd_configs:
      - authorization:
          credentials: "DOKEY"
    relabel_configs:
      # Only scrape targets that have a tag 'monitoring'.
      - source_labels: [__meta_digitalocean_tags]
        regex: \".*,monitoring,.*\"
        action: keep

      # Use the public IPv4 address and port 9100 to scrape the target.
      - source_labels: [__meta_digitalocean_public_ipv4]
        target_label: __address__
        replacement: \"\$1:9100\"

  - job_name: cadvisor

    digitalocean_sd_configs:
      - authorization:
          credentials: "DOKEY"
    relabel_configs:
      # Only scrape targets that have a tag 'monitoring'.
      - source_labels: [__meta_digitalocean_tags]
        regex: \".*,monitoring,.*\"
        action: keep

      - source_labels: [__meta_digitalocean_public_ipv4]
        target_label: __address__
        replacement: \"\$1:8080\"